spring:
    datasource:
        url: jdbc:oracle:thin:@192.168.0.150:1521:ORCL
        username: DW
        password: DW
        driver-class-name: oracle.jdbc.driver.OracleDriver
        
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
                
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 587973436644-c6ce7fr9skhka2jq5btii9us7unlud8f.apps.googleusercontent.com
              clientSecret: qORY6nw7LdrKwL7oAAhwMm2E
              redirectUriTemplate: "http://localhost:4200/login"
              authorization-grant-type: authorization_code
              scope:
                - email
                - profile
server:
      port: 8081

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:4200/login