--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-21-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HEADER
--------------------------------------------------------

  CREATE TABLE "DW"."HEADER" 
   (	"ID_CORRELATIVO" NUMBER(19,0), 
	"ESTADO" VARCHAR2(255 CHAR), 
	"HORARIO" VARCHAR2(255 CHAR), 
	"SECCION" VARCHAR2(255 CHAR), 
	"SEMESTRE" NUMBER(10,0), 
	"ID_CATEDRATICO" NUMBER(19,0), 
	"ID_CENTRO" NUMBER(19,0), 
	"ID_CURSO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Table TC_CATEDRATICO
--------------------------------------------------------

  CREATE TABLE "DW"."TC_CATEDRATICO" 
   (	"ID_CATEDRATICO" NUMBER(19,0), 
	"ESTADO" VARCHAR2(150 CHAR), 
	"NOMBRE" VARCHAR2(150 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Table TC_CENTRO
--------------------------------------------------------

  CREATE TABLE "DW"."TC_CENTRO" 
   (	"ID_CENTRO" NUMBER(19,0), 
	"CORREO" VARCHAR2(150 CHAR), 
	"DIRECCION" VARCHAR2(150 CHAR), 
	"NOMBRE" VARCHAR2(150 CHAR), 
	"TELEFONO" VARCHAR2(20 CHAR), 
	"ID_DEPTO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Table TC_CICLO
--------------------------------------------------------

  CREATE TABLE "DW"."TC_CICLO" 
   (	"ID_CICLO" NUMBER(19,0), 
	"CICLO1" VARCHAR2(150 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Table TC_CURSO
--------------------------------------------------------

  CREATE TABLE "DW"."TC_CURSO" 
   (	"ID_CURSO" NUMBER(19,0), 
	"NOM_CURSO" VARCHAR2(150 CHAR), 
	"ID_CICLO" NUMBER(19,0), 
	"ID_FACULTAD" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Table TC_DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "DW"."TC_DEPARTAMENTO" 
   (	"ID_DEPTO" NUMBER(19,0), 
	"NOM_DEPTO" VARCHAR2(150 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Table TC_DETALLE
--------------------------------------------------------

  CREATE TABLE "DW"."TC_DETALLE" 
   (	"ID_CORRELATIVO" NUMBER(19,0), 
	"ESTADO" VARCHAR2(255 CHAR), 
	"FECHA_DESARROLLAR" TIMESTAMP (6), 
	"FECHA_REVISION" TIMESTAMP (6), 
	"MES" NUMBER(10,0), 
	"PORC_AVANCE_MENSUAL" NUMBER(10,0), 
	"PORC_AVANCE_SEMANAL" NUMBER(10,0), 
	"SUBTEMA" VARCHAR2(255 CHAR), 
	"ID_TEMA" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Table TC_FACULTAD
--------------------------------------------------------

  CREATE TABLE "DW"."TC_FACULTAD" 
   (	"ID_FACULTAD" NUMBER(19,0), 
	"NOMBRE" VARCHAR2(150 CHAR), 
	"ID_CENTRO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Table TC_TEMA
--------------------------------------------------------

  CREATE TABLE "DW"."TC_TEMA" 
   (	"ID_TEMA" NUMBER(19,0), 
	"ESTADO" VARCHAR2(150 CHAR), 
	"NOMBRE" VARCHAR2(150 CHAR), 
	"ID_CORRELATIVO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DW"."USERS" 
   (	"ID" NUMBER(19,0), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"EMAIL_VERIFIED" NUMBER(1,0), 
	"IMAGE_URL" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"PROVIDER" VARCHAR2(255 CHAR), 
	"PROVIDER_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
REM INSERTING into DW.HEADER
SET DEFINE OFF;
Insert into DW.HEADER (ID_CORRELATIVO,ESTADO,HORARIO,SECCION,SEMESTRE,ID_CATEDRATICO,ID_CENTRO,ID_CURSO) values (67,'1','14:00:00','A',8,66,62,65);
REM INSERTING into DW.TC_CATEDRATICO
SET DEFINE OFF;
Insert into DW.TC_CATEDRATICO (ID_CATEDRATICO,ESTADO,NOMBRE) values (66,'1','Melvin Cali');
Insert into DW.TC_CATEDRATICO (ID_CATEDRATICO,ESTADO,NOMBRE) values (1,'1','Test Test');
REM INSERTING into DW.TC_CENTRO
SET DEFINE OFF;
Insert into DW.TC_CENTRO (ID_CENTRO,CORREO,DIRECCION,NOMBRE,TELEFONO,ID_DEPTO) values (61,'amatitlan@umg.edu.gt','guatemala','Amatitlan','66335775',9);
Insert into DW.TC_CENTRO (ID_CENTRO,CORREO,DIRECCION,NOMBRE,TELEFONO,ID_DEPTO) values (62,'bocadelmonte@umg.edu.gt','guatemala','Boca del Monte','24489780',9);
REM INSERTING into DW.TC_CICLO
SET DEFINE OFF;
Insert into DW.TC_CICLO (ID_CICLO,CICLO1) values (64,'8');
REM INSERTING into DW.TC_CURSO
SET DEFINE OFF;
Insert into DW.TC_CURSO (ID_CURSO,NOM_CURSO,ID_CICLO,ID_FACULTAD) values (65,'Desarrollo Web',64,63);
REM INSERTING into DW.TC_DEPARTAMENTO
SET DEFINE OFF;
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (1,'Alta Verapaz');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (2,'Baja Verapaz');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (3,'Chimaltenango');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (4,'Chiquimula');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (5,'Petén');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (6,'El Progreso');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (7,'Quiché');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (8,'Escuintla');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (9,'Guatemala');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (10,'Huehuetenango');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (11,'Izabal');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (12,'Jalapa');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (13,'Jutiapa');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (14,'Quetzaltenango');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (15,'Retalhuleu');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (16,'Sacatepéquez');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (17,'San Marcos');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (18,'Santa Rosa');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (19,'Sololá');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (20,'Suchitepéquez');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (21,'Totonicapán');
Insert into DW.TC_DEPARTAMENTO (ID_DEPTO,NOM_DEPTO) values (22,'Zacapa');
REM INSERTING into DW.TC_DETALLE
SET DEFINE OFF;
Insert into DW.TC_DETALLE (ID_CORRELATIVO,ESTADO,FECHA_DESARROLLAR,FECHA_REVISION,MES,PORC_AVANCE_MENSUAL,PORC_AVANCE_SEMANAL,SUBTEMA,ID_TEMA) values (69,'1',to_timestamp('20/11/19 03:49:52.442353000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('20/11/19 03:49:56.583034000 PM','DD/MM/RR HH12:MI:SSXFF AM'),11,10,1,'Oauth2',68);
Insert into DW.TC_DETALLE (ID_CORRELATIVO,ESTADO,FECHA_DESARROLLAR,FECHA_REVISION,MES,PORC_AVANCE_MENSUAL,PORC_AVANCE_SEMANAL,SUBTEMA,ID_TEMA) values (70,'1',to_timestamp('20/11/19 03:49:52.442000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('20/11/19 03:49:56.583000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),11,10,1,'Oauth2 Google',69);
REM INSERTING into DW.TC_FACULTAD
SET DEFINE OFF;
Insert into DW.TC_FACULTAD (ID_FACULTAD,NOMBRE,ID_CENTRO) values (63,'Ingenieria en sistemas',62);
REM INSERTING into DW.TC_TEMA
SET DEFINE OFF;
Insert into DW.TC_TEMA (ID_TEMA,ESTADO,NOMBRE,ID_CORRELATIVO) values (68,'1','Springboot',67);
Insert into DW.TC_TEMA (ID_TEMA,ESTADO,NOMBRE,ID_CORRELATIVO) values (69,'1','Springboot2',67);
REM INSERTING into DW.USERS
SET DEFINE OFF;
Insert into DW.USERS (ID,EMAIL,EMAIL_VERIFIED,IMAGE_URL,NAME,PASSWORD,PROVIDER,PROVIDER_ID) values (102,'email@email.com',0,null,'Name','$2a$10$71X.v6rEIsIgo967jDxtdeV/mdVStwiTXYMDpNSP1wBit18gLDyHy','local',null);
--------------------------------------------------------
--  DDL for Index SYS_C0013174
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."SYS_C0013174" ON "DW"."HEADER" ("ID_CORRELATIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013178
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."SYS_C0013178" ON "DW"."TC_CATEDRATICO" ("ID_CATEDRATICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013185
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."SYS_C0013185" ON "DW"."TC_CENTRO" ("ID_CENTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013188
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."SYS_C0013188" ON "DW"."TC_CICLO" ("ID_CICLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013193
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."SYS_C0013193" ON "DW"."TC_CURSO" ("ID_CURSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013196
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."SYS_C0013196" ON "DW"."TC_DEPARTAMENTO" ("ID_DEPTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013201
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."SYS_C0013201" ON "DW"."TC_DETALLE" ("ID_CORRELATIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013204
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."SYS_C0013204" ON "DW"."TC_FACULTAD" ("ID_FACULTAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013208
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."SYS_C0013208" ON "DW"."TC_TEMA" ("ID_TEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013164
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."SYS_C0013164" ON "DW"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  DDL for Index UK6DOTKOTT2KJSP8VW4D0M25FB7
--------------------------------------------------------

  CREATE UNIQUE INDEX "DW"."UK6DOTKOTT2KJSP8VW4D0M25FB7" ON "DW"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW" ;
--------------------------------------------------------
--  Constraints for Table HEADER
--------------------------------------------------------

  ALTER TABLE "DW"."HEADER" MODIFY ("ID_CORRELATIVO" NOT NULL ENABLE);
  ALTER TABLE "DW"."HEADER" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DW"."HEADER" MODIFY ("HORARIO" NOT NULL ENABLE);
  ALTER TABLE "DW"."HEADER" MODIFY ("SECCION" NOT NULL ENABLE);
  ALTER TABLE "DW"."HEADER" MODIFY ("SEMESTRE" NOT NULL ENABLE);
  ALTER TABLE "DW"."HEADER" MODIFY ("ID_CATEDRATICO" NOT NULL ENABLE);
  ALTER TABLE "DW"."HEADER" MODIFY ("ID_CENTRO" NOT NULL ENABLE);
  ALTER TABLE "DW"."HEADER" MODIFY ("ID_CURSO" NOT NULL ENABLE);
  ALTER TABLE "DW"."HEADER" ADD PRIMARY KEY ("ID_CORRELATIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TC_CATEDRATICO
--------------------------------------------------------

  ALTER TABLE "DW"."TC_CATEDRATICO" MODIFY ("ID_CATEDRATICO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CATEDRATICO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CATEDRATICO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CATEDRATICO" ADD PRIMARY KEY ("ID_CATEDRATICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TC_CENTRO
--------------------------------------------------------

  ALTER TABLE "DW"."TC_CENTRO" MODIFY ("ID_CENTRO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CENTRO" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CENTRO" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CENTRO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CENTRO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CENTRO" MODIFY ("ID_DEPTO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CENTRO" ADD PRIMARY KEY ("ID_CENTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TC_CICLO
--------------------------------------------------------

  ALTER TABLE "DW"."TC_CICLO" MODIFY ("ID_CICLO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CICLO" MODIFY ("CICLO1" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CICLO" ADD PRIMARY KEY ("ID_CICLO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TC_CURSO
--------------------------------------------------------

  ALTER TABLE "DW"."TC_CURSO" MODIFY ("ID_CURSO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CURSO" MODIFY ("NOM_CURSO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CURSO" MODIFY ("ID_CICLO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CURSO" MODIFY ("ID_FACULTAD" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_CURSO" ADD PRIMARY KEY ("ID_CURSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TC_DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "DW"."TC_DEPARTAMENTO" MODIFY ("ID_DEPTO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_DEPARTAMENTO" MODIFY ("NOM_DEPTO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_DEPARTAMENTO" ADD PRIMARY KEY ("ID_DEPTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TC_DETALLE
--------------------------------------------------------

  ALTER TABLE "DW"."TC_DETALLE" MODIFY ("ID_CORRELATIVO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_DETALLE" MODIFY ("MES" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_DETALLE" MODIFY ("SUBTEMA" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_DETALLE" MODIFY ("ID_TEMA" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_DETALLE" ADD PRIMARY KEY ("ID_CORRELATIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TC_FACULTAD
--------------------------------------------------------

  ALTER TABLE "DW"."TC_FACULTAD" MODIFY ("ID_FACULTAD" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_FACULTAD" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_FACULTAD" ADD PRIMARY KEY ("ID_FACULTAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
  ALTER TABLE "DW"."TC_FACULTAD" MODIFY ("ID_CENTRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TC_TEMA
--------------------------------------------------------

  ALTER TABLE "DW"."TC_TEMA" MODIFY ("ID_TEMA" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_TEMA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_TEMA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DW"."TC_TEMA" ADD PRIMARY KEY ("ID_TEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
  ALTER TABLE "DW"."TC_TEMA" MODIFY ("ID_CORRELATIVO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "DW"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DW"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DW"."USERS" MODIFY ("EMAIL_VERIFIED" NOT NULL ENABLE);
  ALTER TABLE "DW"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DW"."USERS" MODIFY ("PROVIDER" NOT NULL ENABLE);
  ALTER TABLE "DW"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
  ALTER TABLE "DW"."USERS" ADD CONSTRAINT "UK6DOTKOTT2KJSP8VW4D0M25FB7" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DW"  ENABLE;
